### ISSUE TITLE
VS Code extension displaying errors when creating a library

### ISSUE THREAD

**Issue by st-clair-clarke** [qwikifiers/qwik-nx#132]
### Current Behavior

nx-generate command for qwik-nx library generation not recognizing the workspace libs directory. See ScreenShot attached.
![qwik-nx-2023-04-20_19-29](https://user-images.githubusercontent.com/3227590/233514067-7dab401e-9548-4e28-865b-bff29ee7aa58.png)

### Expected Behavior

The nx executor recognizes the root libs directory.

### Steps to Reproduce

1.

### Nx Report

```shell
*  The terminal process "/usr/bin/bash '-c', 'pnpm exec nx generate qwik-nx:library registration --buildable --directory=libs/medsoft --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: pnpm exec nx generate qwik-nx:library registration --buildable --directory=libs --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run 


>  NX  Generating qwik-nx:library


 >  NX   Cannot find configuration for 'libs-registration'

   Pass --verbose to see the stacktrace.


 *  The terminal process "/usr/bin/bash '-c', 'pnpm exec nx generate qwik-nx:library registration --buildable --directory=libs --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Additional Information

Other nx generators working fine. 

**"qwik-nx": "0.15.4"**

**Comment by dmitry-stepanenko** [comment]
Hi @st-clair-clarke, thank you for raising the issue. 

Can you please rerun in your terminal `pnpm exec nx generate qwik-nx:library registration --buildable --directory=libs/medsoft --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run --verbose` and attach error logs here?

Also please provide the output of `pnpm exec nx report`, this will help to debug the issue.

**Comment by st-clair-clarke** [comment]
running: pnpm exec nx generate qwik-nx:library registration --buildable --directory=libs/medsoft --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run --verbose

Result below:
```
~/../qwik-workspace> nx generate qwik-nx:library registration --buildable --directory=libs/medsoft --importPath=@medsoft/registration --storybookConfiguration --style=scss --tags=registration --no-interactive --dry-run --verbose

>  NX  Generating qwik-nx:library


 >  NX   Cannot find configuration for 'libs-medsoft-registration'


Error: Cannot find configuration for 'libs-medsoft-registration'
    at readProjectConfiguration (/home/ted/workspace/qwik/qwik-workspace/node_modules/.pnpm/nx@15.9.2/node_modules/nx/src/generators/utils/project-configuration.js:90:15)
    at ensureRootTsxExists (/home/ted/workspace/qwik/qwik-workspace/node_modules/.pnpm/qwik-nx@0.15.4_eslint@8.38.0_nx@15.9.2_typescript@5.0.4_vite@4.3.1_vitest@0.30.1/node_modules/qwik-nx/src/utils/ensure-file-utils.js:9:65)
    at /home/ted/workspace/qwik/qwik-workspace/node_modules/.pnpm/qwik-nx@0.15.4_eslint@8.38.0_nx@15.9.2_typescript@5.0.4_vite@4.3.1_vitest@0.30.1/node_modules/qwik-nx/src/generators/library/generator.js:56:53
    at Generator.next (<anonymous>)
    at fulfilled (/home/ted/workspace/qwik/qwik-workspace/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
 ```


**Runing pnpm exec nx report**

```~/workspace/qwik/qwik-workspace> pnpm exec nx report                           04/21/2023 03:52:16 PM

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   pnpm : 8.3.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/vite              : 15.9.2
   @nrwl/nx-cloud          : 16.0.1
   typescript              : 5.0.4
   ---------------------------------------
   Community plugins:
   qwik-nx : 0.15.4


```

**Comment by dmitry-stepanenko** [comment]
@st-clair-clarke so looks like you're running it incorrectly, you shouldn't include `libs` in the directory path. If you run it with `--directory=medsoft`, you will get your library created as you want it to. 

It's not specific to the qwik-nx plugin, that's mostly how nx behaves. You can verify it by trying to create angular/react library using nx executors with `--directory=libs/medsoft` flag, same error should appear. 

Let me know if that solves your problem.

**Comment by st-clair-clarke** [comment]
Thanks.
