### ISSUE TITLE
@nx/storybook@v17.2.5 configuration expects schema.project to be projectName

### ISSUE THREAD

**Issue by arkD** [qwikifiers/qwik-nx#220]
### Current Behavior

Adding storybook to an existing project or when creating a new project, throws an error.

### Expected Behavior

qwik-nx to generate storybook files

### Steps to Reproduce

1. I ran `nx generate qwik-nx:lib --directory=libs/api --name api --storybookConfiguration --style css`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : win32-x64
   yarn   : 4.0.2

   nx (global)        : 17.2.5  (also tried on 17.1.3)
   nx                 : v17.2.5
   @nx/js             : v17.2.5
   @nx/linter         : v17.2.5
   @nx/eslint         : v17.2.5
   @nx/workspace      : v17.2.5
   @nx/cypress        : v17.2.5
   @nx/devkit         : v17.2.5
   @nx/eslint-plugin  : v17.2.5
   @nx/storybook      : v17.2.5
   @nrwl/tao          : v17.2.5
   @nx/vite           : v17.2.5
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   qwik-nx : 2.0.2
```

### Failure Logs

```shell
Error: Cannot find configuration for 'undefined'
    at readProjectConfiguration (D:\projects\lionwholesalesoftware\node_modules\nx\src\generators\utils\project-configuration.js:99:15)
    at configurationGenerator (D:\projects\lionwholesalesoftware\node_modules\@nx\storybook\src\generators\configuration\configuration.js:18:82)
    at D:\projects\lionwholesalesoftware\node_modules\qwik-nx\src\generators\storybook-configuration\generator.js:39:15
    at Generator.next (<anonymous>)
    at fulfilled (D:\projects\lionwholesalesoftware\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional Information

I found an easy workaround by adding `project: normalizedOptions.name,`  to storybookConfigurationGenerator in configurationGenerator of qwik-nx/src/generators/storybook-configuration/generator.js

**Comment by dmitry-stepanenko** [comment]
Thanks for reporting this. Has been fixed a while ago by https://github.com/qwikifiers/qwik-nx/pull/224
