### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by ppusapati** [qwikifiers/qwik-nx#236]
when upgraded to "@builder.io/qwik": "^1.8.0" am getting this error

```
TypeError: Cannot read properties of undefined (reading 'push')
````

```
HOST    |     at D:\web\node_modules\.pnpm\qwik-nx@2.3.0_ixteyxtpp6eguk2j7ybpphsv5m\node_modules\qwik-nx\src\plugins\qwik-nx-vite.plugin.js:36:47
HOST    |     at Generator.next (<anonymous>)
HOST    |     at fulfilled (D:\web\node_modules\.pnpm\tslib@2.7.0\node_modules\tslib\tslib.js:166:62)
HOST    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
when downgrading to "@builder.io/qwik": "^1.7.3" it works as expected. 

am using
@nx/js": "19.6.2",
 "qwik-nx": "2.3.0"

**Comment by dmitry-stepanenko** [comment]
@ppusapati for now please try manually removing the `qwikNxVite` from your vite config. I'll provide a migration to do this.
