### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace') when Generating App on NX 20

### ISSUE THREAD

**Issue by mainawycliffe** [qwikifiers/qwik-nx#240]
### Current Behavior

After updating to NX@20, I am getting the following error: TypeError: Cannot read properties of undefined (reading 'replace'), seems like something internally changed in nx and hence the need to update this plugin to the latest version

### Expected Behavior

Should generate an nx application

### Steps to Reproduce

1. Update to NX V20 or Setup with NX V20
2. Run `pnpm nx generate qwik-nx:app`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.5.0

nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.2
@nx/devkit         : 20.1.2
@nx/esbuild        : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/playwright     : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@ngrx/signals                    : 18.0.2
@nx-toolkits/firebase            : 0.7.6
@testing-library/angular         : 17.3.0
ngx-toastr                       : 19.0.0
qwik-nx                          : 2.3.1
```

### Failure Logs

```shell
NX  Generating qwik-nx:application

✔ What name would you like to use? · portals
✔ Which stylesheet format would you like to use? · scss

 NX   Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeWindowsDriveLetter (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/src/utils/path.js:9:27)
    at normalizePath (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/src/utils/path.js:16:12)
    at determineProjectNameAndRootOptions (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/@nx+devkit@20.1.2_nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@s_sgse4sppmhp6dh24rnls7tj7ui/node_modules/@nx/devkit/src/generators/project-name-and-root-utils.js:11:58)
    at /Users/mainawycliffe/projects/myyard/node_modules/.pnpm/qwik-nx@2.3.1_twjjklwevhsczmotghfoqxella/node_modules/qwik-nx/src/generators/application/utils/normalize-options.js:11:180
    at Generator.next (<anonymous>)
    at /Users/mainawycliffe/projects/myyard/node_modules/.pnpm/tslib@2.7.0/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/tslib@2.7.0/node_modules/tslib/tslib.js:165:16)
    at normalizeOptions (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/qwik-nx@2.3.1_twjjklwevhsczmotghfoqxella/node_modules/qwik-nx/src/generators/application/utils/normalize-options.js:10:20)
    at /Users/mainawycliffe/projects/myyard/node_modules/.pnpm/qwik-nx@2.3.1_twjjklwevhsczmotghfoqxella/node_modules/qwik-nx/src/generators/application/generator-internal.js:23:82
```

**Comment by dmitry-stepanenko** [comment]
qwik-nx v3 has been released
