### ISSUE TITLE
Preview failing in NX 20 

### ISSUE THREAD

**Issue by mainawycliffe** [qwikifiers/qwik-nx#241]
### Current Behavior

Fails to do a preview build

### Expected Behavior

Should buiild successfully and allow preview

### Steps to Reproduce

1. Run `nx run portals:preview`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.5.0

nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.2
@nx/devkit         : 20.1.2
@nx/esbuild        : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/playwright     : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@ngrx/signals                    : 18.0.2
@nx-toolkits/firebase            : 0.7.6
@testing-library/angular         : 17.3.0
ngx-toastr                       : 19.0.0
qwik-nx                          : 2.3.1
```

### Failure Logs

```shell
Error: qwikCity plugin "routesDir" not found: Error: ENOENT: no such file or directory, stat '/Users/mainawycliffe/projects/myyard/src/routes'
    at validatePlugin (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/@builder.io+qwik-city@1.10.0_acorn@8.12.1_rollup@4.27.3_typescript@5.5.4_vite@5.2.14_@types+n_v4s5rxyzf2za5nbdmmih23gmqu/node_modules/@builder.io/qwik-city/lib/vite/index.cjs:22243:11)
    at async configResolved (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/@builder.io+qwik-city@1.10.0_acorn@8.12.1_rollup@4.27.3_typescript@5.5.4_vite@5.2.14_@types+n_v4s5rxyzf2za5nbdmmih23gmqu/node_modules/@builder.io/qwik-city/lib/vite/index.cjs:27280:7)
    at async Promise.all (index 1)
    at async resolveConfig (file:///Users/mainawycliffe/projects/myyard/node_modules/.pnpm/vite@5.2.14_@types+node@18.16.9_less@4.1.3_sass@1.56.2_stylus@0.64.0_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:69696:5)
    at async vitePreviewServerExecutor (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/@nx+vite@20.1.2_@babel+traverse@7.25.9_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers_x5ah45ymkza2kp3kx6eea55nfa/node_modules/@nx/vite/src/executors/preview-server/preview-server.impl.js:43:22)
    at async getLastValueFromAsyncIterableIterator (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/src/utils/async-iterator.js:15:19)
    at async iteratorToProcessStatusCode (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/src/command-line/run/run.js:39:25)
    at async handleErrors (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async process.<anonymous> (/Users/mainawycliffe/projects/myyard/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.12__@swc+types@0.1.17_ty_ebfgdql3et2pzmvihir237ihuy/node_modules/nx/bin/run-executor.js:59:28)
```

**Comment by dmitry-stepanenko** [comment]
hey @mainawycliffe thank you for raising this. I have a draft for nx20 support, will ship it in the nearest future

**Comment by dmitry-stepanenko** [comment]
qwik-nx v3 has been released

**Comment by mainawycliffe** [comment]
@dmitry-stepanenko thanks
